/**
 * The pictures in the hero's collection that are not drawn but found: public
 * domain and CC0 works — statues, strange and old art, the Renaissance and the
 * great paintings after it, Egyptian tomb walls, the sea, European watercolour
 * landscapes, Jupiter, a black hole, and plant cells — and a hundred works of
 * human culture from around the world: Mesopotamia and Persia, Africa, the
 * ancient Americas, the Pacific, South and Southeast Asia (Thailand among
 * them), the Himalayas, China, Korea, Japan, the Islamic world and Egypt.
 *
 * Sources: The Met's Open Access (CC0), NASA (not subject to copyright), and
 * Wikimedia Commons files marked public domain. Credits are shown with the
 * picture anyway: it is the decent thing, and NASA asks for it.
 *
 * Files live in /public/hero (1920px WebP) and /public/hero/thumb (600px tall,
 * used by the opening timelapse — at 300px the full-screen frames came out
 * visibly soft).
 */

export interface HeroPhoto {
  id: string
  title: string
  by: string
  date: string
  source: string
  url: string
  /** CSS object-position — where the subject is, for the crop. */
  focus?: string
  /** Busy by default (the orb frosts over it); false for the calm ones. */
  busy?: boolean
}

export const PHOTOS: HeroPhoto[] = [
  { id: 'perseus', title: 'Perseus with the Head of Medusa', by: 'Antonio Canova', date: '1804–6', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/204758', focus: '50% 20%' },
  { id: 'ugolino', title: 'Ugolino and His Sons', by: 'Jean-Baptiste Carpeaux', date: '1865–67', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/204812', focus: '50% 25%' },
  { id: 'kouros', title: 'Marble statue of a kouros (youth)', by: 'Greek, Attic', date: 'ca. 590–580 BCE', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/253370', focus: '50% 18%' },
  { id: 'amazon', title: 'Marble statue of a wounded Amazon', by: 'Roman', date: '1st–2nd century CE', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/253373', focus: '50% 20%' },
  { id: 'warrior', title: 'Marble statue of a wounded warrior', by: 'Roman', date: 'ca. 138–181 CE', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/251929', focus: '50% 20%' },
  { id: 'island-of-the-dead', title: 'Island of the Dead', by: 'Arnold Böcklin', date: '1880', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/435683', busy: false },
  { id: 'melencolia', title: 'Melencolia I', by: 'Albrecht Dürer', date: '1514', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/336228' },
  { id: 'sleep-of-reason', title: 'The Sleep of Reason Produces Monsters, Los Caprichos pl. 43', by: 'Francisco de Goya', date: '1799', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/338473' },
  { id: 'harvesters', title: 'The Harvesters', by: 'Pieter Bruegel the Elder', date: '1565', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/435809' },
  { id: 'great-wave', title: 'Under the Wave off Kanagawa (The Great Wave)', by: 'Katsushika Hokusai', date: 'ca. 1830–32', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/45434' },
  { id: 'hollar-wave', title: 'Warship in the trough of a wave', by: 'Wenceslaus Hollar', date: '1665', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/361774' },
  { id: 'cotman-storm', title: 'Boats off the coast, storm approaching', by: 'John Sell Cotman', date: '1830', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/746834' },
  { id: 'lindisfarne', title: 'Lindisfarne Castle, Holy Island, Northumberland', by: 'Thomas Girtin', date: '1796–97', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/341793' },
  { id: 'norwich', title: 'River at Norwich', by: 'Thomas Girtin', date: 'early 19th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/341795' },
  { id: 'rievaulx', title: 'The east end of Rievaulx Abbey, Yorkshire', by: 'John Sell Cotman', date: '1803', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/373905' },
  { id: 'ruined-castle', title: 'Ruined Castle', by: 'John Sell Cotman', date: '1823–42', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/341084' },
  { id: 'windsor', title: 'Windsor Great Park', by: 'Paul Sandby', date: '1790–99', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/359037' },
  { id: 'lake-zug', title: 'The Lake of Zug', by: 'Joseph Mallord William Turner', date: '1843', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/337499' },
  { id: 'venice', title: 'Venice, from the Porch of Madonna della Salute', by: 'Joseph Mallord William Turner', date: 'ca. 1835', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/437853' },
  { id: 'saltash', title: 'Saltash with the Water Ferry, Cornwall', by: 'Joseph Mallord William Turner', date: '1811', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/437852' },
  { id: 'greenwich', title: 'View of London from Greenwich', by: 'Joseph Mallord William Turner', date: '1825', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/356768' },
  { id: 'wales', title: 'River Landscape in Wales', by: 'David Cox', date: 'ca. 1850', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/341093' },
  { id: 'harlech', title: 'Harlech Castle across the Traeth Mawr', by: 'John Varley', date: '1800–42', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/373907' },
  { id: 'warwick', title: 'Warwick Castle', by: 'Canaletto (Giovanni Antonio Canal)', date: '1748', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/438106' },
  { id: 'prout-coast', title: 'Coastal Scene with Beached Boats in Foreground', by: 'Samuel Prout', date: 'early–mid 19th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/364449' },
  { id: 'jupiter-bands', title: 'Jupiter\'s Bands of Clouds', by: 'NASA / JPL-Caltech / SwRI / MSSS', date: '', source: 'NASA', url: 'https://images.nasa.gov/details/PIA21393', busy: false },
  { id: 'jupiter-chaos', title: 'Jupiter\'s Colourful, Chaotic Clouds', by: 'NASA / JPL-Caltech / SwRI / MSSS', date: '', source: 'NASA', url: 'https://images.nasa.gov/details/PIA25729', busy: false },
  { id: 'black-hole', title: 'Black Hole Accretion Disk Visualization', by: 'NASA\'s Goddard Space Flight Center / Jeremy Schnittman', date: '2019', source: 'NASA', url: 'https://svs.gsfc.nasa.gov/13326', busy: false },
  { id: 'creation-of-adam', title: 'The Creation of Adam', by: 'Michelangelo', date: 'ca. 1508–12', source: 'Wikimedia Commons (public domain)', url: 'https://commons.wikimedia.org/wiki/File:Michelangelo_-_Creation_of_Adam_(cropped).jpg', focus: '45% 50%' },
  { id: 'school-of-athens', title: 'The School of Athens', by: 'Raphael', date: '1509–11', source: 'Wikimedia Commons (public domain)', url: 'https://commons.wikimedia.org/wiki/File:%22The_School_of_Athens%22_by_Raffaello_Sanzio_da_Urbino.jpg' },
  { id: 'birth-of-venus', title: 'The Birth of Venus', by: 'Sandro Botticelli', date: 'ca. 1484–86', source: 'Wikimedia Commons (public domain)', url: 'https://commons.wikimedia.org/wiki/File:Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_ProjectFXD.jpg' },
  { id: 'primavera', title: 'Primavera', by: 'Sandro Botticelli', date: 'ca. 1480', source: 'Wikimedia Commons (public domain)', url: 'https://commons.wikimedia.org/wiki/File:Sandro_Botticelli_-_La_Primavera_-_Google_Art_Project.jpg' },
  { id: 'last-supper', title: 'The Last Supper', by: 'Leonardo da Vinci', date: '1495–98', source: 'Wikimedia Commons (public domain)', url: 'https://commons.wikimedia.org/wiki/File:%C3%9Altima_Cena_-_Da_Vinci_5.jpg' },
  { id: 'last-judgement', title: 'The Last Judgement', by: 'Michelangelo', date: '1536–41', source: 'Wikimedia Commons (public domain)', url: 'https://commons.wikimedia.org/wiki/File:Last_Judgement_(Michelangelo).jpg', focus: '50% 30%' },
  { id: 'garden-delights', title: 'The Garden of Earthly Delights', by: 'Hieronymus Bosch', date: 'ca. 1490–1510', source: 'Wikimedia Commons (public domain)', url: 'https://commons.wikimedia.org/wiki/File:The_Garden_of_Earthly_Delights_by_Bosch_High_Resolution.jpg' },
  { id: 'tower-of-babel', title: 'The Tower of Babel', by: 'Pieter Bruegel the Elder', date: '1563', source: 'Wikimedia Commons (public domain)', url: 'https://commons.wikimedia.org/wiki/File:Pieter_Bruegel_the_Elder_-_The_Tower_of_Babel_(Vienna)_-_Google_Art_Project_-_edited.jpg' },
  { id: 'rebel-angels', title: 'The Fall of the Rebel Angels', by: 'Pieter Bruegel the Elder', date: '1562', source: 'Wikimedia Commons (public domain)', url: 'https://commons.wikimedia.org/wiki/File:Pieter_Bruegel_the_Elder_-_The_Fall_of_the_Rebel_Angels_-_Google_Art_Project.jpg' },
  { id: 'triumph-of-death', title: 'The Triumph of Death', by: 'Pieter Bruegel the Elder', date: 'ca. 1562', source: 'Wikimedia Commons (public domain)', url: 'https://commons.wikimedia.org/wiki/File:The_Triumph_of_Death_by_Pieter_Bruegel_the_Elder.jpg' },
  { id: 'ambassadors', title: 'The Ambassadors', by: 'Hans Holbein the Younger', date: '1533', source: 'Wikimedia Commons (public domain)', url: 'https://commons.wikimedia.org/wiki/File:Hans_Holbein_the_Younger_-_The_Ambassadors_-_Google_Art_Project.jpg', focus: '50% 40%' },
  { id: 'night-watch', title: 'The Night Watch', by: 'Rembrandt van Rijn', date: '1642', source: 'Wikimedia Commons (public domain)', url: 'https://commons.wikimedia.org/wiki/File:The_Nightwatch_by_Rembrandt_-_Rijksmuseum.jpg', focus: '45% 45%' },
  { id: 'death-of-socrates', title: 'The Death of Socrates', by: 'Jacques Louis David', date: '1787', source: 'Wikimedia Commons (CC0)', url: 'https://commons.wikimedia.org/wiki/File:The_Death_of_Socrates_MET_DT40.jpg' },
  { id: 'raft-medusa', title: 'The Raft of the Medusa', by: 'Théodore Géricault', date: '1818–19', source: 'Wikimedia Commons (public domain)', url: 'https://commons.wikimedia.org/wiki/File:JEAN_LOUIS_TH%C3%89ODORE_G%C3%89RICAULT_-_La_Balsa_de_la_Medusa_(Museo_del_Louvre,_1818-19).jpg' },
  { id: 'liberty', title: 'Liberty Leading the People', by: 'Eugène Delacroix', date: '1830', source: 'Wikimedia Commons (public domain)', url: 'https://commons.wikimedia.org/wiki/File:Eug%C3%A8ne_Delacroix_-_La_libert%C3%A9_guidant_le_peuple.jpg', focus: '55% 30%' },
  { id: 'wanderer', title: 'Wanderer above the Sea of Fog', by: 'Caspar David Friedrich', date: 'ca. 1818', source: 'Wikimedia Commons (public domain)', url: 'https://commons.wikimedia.org/wiki/File:Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg', focus: '50% 35%' },
  { id: 'starry-night', title: 'The Starry Night', by: 'Vincent van Gogh', date: '1889', source: 'Wikimedia Commons (public domain)', url: 'https://commons.wikimedia.org/wiki/File:Vincent_van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg' },
  { id: 'the-kiss', title: 'The Kiss', by: 'Gustav Klimt', date: '1907–08', source: 'Wikimedia Commons (public domain)', url: 'https://commons.wikimedia.org/wiki/File:The_Kiss_-_Gustav_Klimt_-_Google_Cultural_Institute.jpg', focus: '50% 35%' },
  { id: 'nebamun', title: 'Nebamun hunting in the marshes, tomb of Nebamun', by: 'Egyptian, Thebes', date: 'ca. 1350 BCE', source: 'Wikimedia Commons (public domain)', url: 'https://commons.wikimedia.org/wiki/File:Tomb_of_Nebamun.jpg', focus: '50% 40%' },
  { id: 'nakht', title: 'North Side of the West Wall of Nakht\'s Offering Chapel', by: 'Norman de Garis Davies', date: '1908–1914; original ca. 1410–1370 BCE', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/548578' },
  { id: 'desmidiea', title: 'Desmidiea, Kunstformen der Natur', by: 'Ernst Haeckel', date: '1904', source: 'Wikimedia Commons (public domain)', url: 'https://commons.wikimedia.org/wiki/File:Haeckel_Desmidiea.jpg', focus: '50% 40%' },
  { id: 'diatomea', title: 'Diatomea, Kunstformen der Natur', by: 'Ernst Haeckel', date: '1904', source: 'Wikimedia Commons (public domain)', url: 'https://commons.wikimedia.org/wiki/File:Haeckel_Diatomea.jpg', focus: '50% 40%' },
  { id: 'muscinae', title: 'Muscinae, Kunstformen der Natur', by: 'Ernst Haeckel', date: '1904', source: 'Wikimedia Commons (public domain)', url: 'https://commons.wikimedia.org/wiki/File:Haeckel_Muscinae.jpg', focus: '50% 50%' },
  { id: 'hooke-cork', title: 'Cork cells, Micrographia', by: 'Robert Hooke', date: '1665', source: 'Wikimedia Commons (public domain)', url: 'https://commons.wikimedia.org/wiki/File:Cork_Micrographia_Hooke.png', focus: '50% 45%' },
  // Human culture, around the world. The Met Open Access (CC0) highlights.
  { id: 'statue-gudea-named-gudea', title: 'Statue of Gudea, named “Gudea, the man who built the temple, may his life be long”', by: 'Neo-Sumerian', date: 'ca. 2090 BCE', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/329072', focus: '50% 30%' },
  { id: 'human-headed-winged-bull', title: 'Human-headed winged bull (lamassu)', by: 'Assyrian', date: 'ca. 883–859 BCE', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/322608' },
  { id: 'panel-striding-lion', title: 'Panel with striding lion', by: 'Babylonian', date: 'ca. 604–562 BCE', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/322585' },
  { id: 'orthostat-relief-lion-hunt', title: 'Orthostat relief: lion-hunt scene', by: 'Hittite', date: 'ca. 10th−9th century BCE', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/324008' },
  { id: 'relief-panel', title: 'Relief panel', by: 'Assyrian', date: 'ca. 883–859 BCE', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/322611' },
  { id: 'plate-hunting-scene-tale', title: 'Plate with a hunting scene from the tale of Bahram Gur and Azadeh', by: 'Sasanian', date: 'ca. 5th century CE', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/327497' },
  { id: 'kneeling-bull-holding-spouted', title: 'Kneeling bull holding a spouted vessel', by: 'Proto-Elamite', date: 'ca. 3100–2900 BCE', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/329074', focus: '50% 30%' },
  { id: 'standing-male-worshiper', title: 'Standing male worshiper', by: 'Sumerian', date: 'ca. 2900–2600 BCE', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/323735', focus: '50% 30%' },
  { id: 'mangaaka-power-figure', title: 'Mangaaka Power Figure (Nkisi N’Kondi)', by: 'Yombe-Kongo artist and nganga (ritual specialist)', date: 'ca. 1880–1900', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/320053' },
  { id: 'pendant-mask-iyoba-idia', title: 'Pendant mask of Ìyọ́bà Idià', by: 'Ìgbèsànmwà (ivory- and wood- carving guild) artists', date: '16th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/318622', focus: '50% 30%' },
  { id: 'plaque-warrior-attendants', title: 'Plaque with Warrior and Attendants', by: 'Ìgùn Ẹ́rọ̀nwwọ̀n (brass-casting guild) artists', date: 'ca. 1540–70', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/316393', focus: '50% 30%' },
  { id: 'uhunmwelao', title: 'Ùhúnmwèlaò (head of an ọ́bà)', by: 'Ìgùn Ẹ́rọ̀nwwọ̀n (brass-casting guild) artists', date: 'Early 15th–mid-16th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/312290' },
  { id: 'priest-raised-arms', title: 'Priest with raised arms', by: 'Dogon blacksmith', date: '14th–17th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/310765', focus: '50% 30%' },
  { id: 'seated-couple', title: 'Seated couple', by: '"Barnes Foundation Master"', date: '18th–early 19th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/310325', focus: '50% 30%' },
  { id: 'nlo-byeri', title: 'Nlô byeri (reliquary guardian head)', by: 'Betsi-Fang artist', date: '19th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/312429', focus: '50% 30%' },
  { id: 'mwanangana-playing-sanza', title: 'Mwanangana (lord of the land) playing a sanza', by: 'Chokwe artist', date: '19th century (before 1869)', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/316173', focus: '50% 30%' },
  { id: 'helmet-crest-nja-masquerade', title: 'Helmet crest from a nja masquerade', by: 'Grassfields artists', date: 'ca. 1800–80', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/311021', focus: '50% 30%' },
  { id: 'nsodie', title: 'Nsodie (memorial head)', by: 'Akan artist', date: '17th–mid-18th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/311024', focus: '50% 30%' },
  { id: 'gwandusu', title: 'Gwandusu', by: 'Bamana numu (blacksmith)', date: '15th–17th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/312336', focus: '50% 30%' },
  { id: 'book-gospels', title: 'Book of the Gospels', by: 'Northern Highlands artist', date: 'late 14th–early 15th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/317618', focus: '50% 30%' },
  { id: 'masqala-q-ddase', title: 'Mäsqälä qǝddase (liturgical cross)', by: 'Ezra', date: 'ca. 1500', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/317196', focus: '50% 30%' },
  { id: 'relief-enthroned-ruler', title: 'Relief with enthroned ruler', by: 'Chakalte\'', date: '770 CE', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/313240' },
  { id: 'censer-seated-king', title: 'Censer with seated king', by: 'Maya artist(s)', date: '300–400 CE', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/318345', focus: '50% 30%' },
  { id: 'vessel-mythological-scene', title: 'Vessel with mythological scene', by: 'Metropolitan Painter', date: '600–800 CE', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/310364', focus: '50% 30%' },
  { id: 'mirror-bearer', title: 'Mirror-bearer', by: 'Maya artist(s)', date: '410–650 CE', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/313256', focus: '50% 30%' },
  { id: 'chalchiuhtlicue', title: 'Chalchiuhtlicue', by: 'Mexica artist(s)', date: '1325–1521 CE', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/307651', focus: '50% 30%' },
  { id: 'funerary-mask', title: 'Funerary mask', by: 'Lambayeque (Sicán) artist(s)', date: '900–1100 CE', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/309959' },
  { id: 'tunic-confronting-catfish', title: 'Tunic with Confronting Catfish', by: 'Nasca-Wari', date: '800–850 CE', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/307975' },
  { id: 'seated-hollow-figure-helmet', title: 'Seated hollow figure with helmet', by: 'Las Bocas artist(s)', date: '1200–800 BCE', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/313327' },
  { id: 'smiling-figure', title: 'Smiling figure (Sonriente)', by: 'South central Veracruz artist(s)', date: '600–1000 CE', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/313386' },
  { id: 'male-figure', title: 'Male Figure (Moai Tangata)', by: 'Rapa Nui people', date: 'early 19th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/314826', focus: '50% 30%' },
  { id: 'amo', title: 'Amo (house post figure)', by: 'Māori artist', date: 'ca. 1800', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/313697', focus: '50% 30%' },
  { id: 'krar', title: 'Krar (mask)', by: 'Mabuiag Island artist', date: 'mid to late 19th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/311950' },
  { id: 'palepai-maju', title: 'Palepai maju (ceremonial banner)', by: 'Paminggir artists', date: '18th–19th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/316457' },
  { id: 'standing-buddha', title: 'Standing Buddha', by: 'Thailand (Nakhon Pathom Province)', date: '8th–9th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/38954', focus: '50% 30%' },
  { id: 'seated-buddha', title: 'Seated Buddha', by: 'Thailand', date: 'first half of the 13th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/39107', focus: '50% 30%' },
  { id: 'seated-ganesha', title: 'Seated Ganesha', by: 'Thailand', date: 'ca. 15th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/39111', focus: '50% 30%' },
  { id: 'buddha-protected-by-seven', title: 'Buddha Protected by a Seven-headed Naga', by: 'Cambodia', date: 'late 12th–early 13th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/38451', focus: '50% 30%' },
  { id: 'standing-ganesha', title: 'Standing Ganesha', by: 'Cambodia', date: 'second half 7th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/38159', focus: '50% 30%' },
  { id: 'bust-hevajra', title: 'Bust of Hevajra', by: 'Cambodia', date: 'late 12th–early 13th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/38304', focus: '50% 30%' },
  { id: 'standing-shiva-or-temple', title: 'Standing Shiva or Temple Guardian (Dvarapala)', by: 'Vietnam (Champa)', date: 'ca. first half of the 10th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/38314', focus: '50% 30%' },
  { id: 'royal-processions-ceremonies-entertainments', title: 'Royal processions, ceremonies and entertainments', by: 'Court of King Mindon or Thibaw, or associated workshops', date: '1870s–1880s', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/744940' },
  { id: 'shiva-as-lord-dance', title: 'Shiva as Lord of Dance (Nataraja)', by: 'Indian (Tamil Nadu)', date: 'ca. late 11th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/39328', focus: '50% 30%' },
  { id: 'krishna-balarama-fight-evil', title: 'Krishna and Balarama Fight the Evil King Kamsa’s Wrestlers: Page from a Dispersed Bhagavata Purana', by: 'India (Madhya Pradesh, Malwa)', date: 'ca. 1650', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/37886' },
  { id: 'lady-playing-tanpura', title: 'A Lady Playing the Tanpura', by: 'India (Rajasthan, Kishangarh)', date: 'ca. 1735', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/38038', focus: '50% 30%' },
  { id: 'shiva-parvati-playing-chaupar', title: 'Shiva and Parvati Playing Chaupar: Folio from a Rasamanjari Series', by: 'Devidasa of Nurpur', date: 'dated 1694–95', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/37942' },
  { id: 'pichhwai-for-festival-cows', title: 'Pichhwai for the Festival of Cows', by: 'India, Deccan, Aurangabad (?)', date: 'late 18th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/65576' },
  { id: 'palampore', title: 'Palampore', by: 'India (Coromandel Coast), for the Sri Lankan market', date: 'first quarter of the 18th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/75909', focus: '50% 30%' },
  { id: 'maharana-sangram-singh-riding', title: 'Maharana Sangram Singh Riding a Prize Stallion', by: 'Stipple Master', date: 'ca. 1712', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/72589' },
  { id: 'goddess-durga-slaying-demon', title: 'Goddess Durga Slaying the Demon Mahisha', by: 'Eastern India, Bihar, probably Gaya district', date: 'second half of the 9th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/719420', focus: '50% 30%' },
  { id: 'drum-panel-scenes-great', title: 'Drum panel with scenes of the Great Departure and Temptation of the Buddha', by: 'India, Nagarjunakonda, Guntur district, Andhra Pradesh', date: 'first half 3rd century CE', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/38239', focus: '50% 30%' },
  { id: 'mandala-raktayamari', title: 'Mandala of Raktayamari', by: 'Mikyo Dorje', date: 'late 14th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/78193', focus: '50% 30%' },
  { id: 'guru-dragpo-padmasambhavas-fierce', title: 'Guru Dragpo, Padmasambhava’s Fierce Emanation', by: 'Tibet', date: '18th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/682118', focus: '50% 30%' },
  { id: 'thousand-armed-chenresi-cosmic', title: 'Thousand-Armed Chenresi, a Cosmic Form of the Bodhisattva Avalokiteshvara', by: 'Tibet', date: '14th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/37799' },
  { id: 'ushnishavijaya-enthroned-womb-stupa', title: 'Ushnishavijaya Enthroned in the Womb of a Stupa', by: 'Nepal', date: 'dated 1510–19', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/78188', focus: '50% 30%' },
  { id: 'chakrasamvara-mandala', title: 'Chakrasamvara Mandala', by: 'Nepal', date: 'ca. 1100', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/38021', focus: '50% 30%' },
  { id: 'bhairava', title: 'Bhairava', by: 'Nepal, Kathmandu Valley', date: '16th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/78187' },
  { id: 'buddha-expounding-dharma', title: 'Buddha Expounding the Dharma', by: 'Sri Lanka (Anuradhapura)', date: 'late 8th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/74832', focus: '50% 30%' },
  { id: 'kangxi-emperors-southern-inspection', title: 'The Kangxi Emperor\'s Southern Inspection Tour, Scroll Three: Ji\'nan to Mount Tai', by: 'Wang Hui', date: 'datable to 1698', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/49156' },
  { id: 'summer-mountains', title: 'Summer Mountains', by: 'Qu Ding', date: 'ca. 1050', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/39915' },
  { id: 'night-shining-white', title: 'Night-Shining White', by: 'Han Gan', date: 'ca. 750', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/39901' },
  { id: 'sixteen-luohans', title: 'The Sixteen Luohans', by: 'Wu Bin', date: 'dated 1591', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/48948' },
  { id: 'arhat', title: 'Arhat (Luohan)', by: 'China', date: 'ca. 1000', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/44799', focus: '50% 30%' },
  { id: 'buddha-maitreya-altarpiece', title: 'Buddha Maitreya (Mile) Altarpiece', by: 'China', date: 'dated 524 (5th year of Zhengguang reign)', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/42162', focus: '50% 30%' },
  { id: 'cosmological-mandala-mount-meru', title: 'Cosmological Mandala with Mount Meru', by: 'China', date: '14th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/39738' },
  { id: 'pensive-bodhisattva', title: 'Pensive bodhisattva', by: 'Korea', date: 'mid-7th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/65397', focus: '50% 30%' },
  { id: 'portrait-yun-dongseom', title: 'Portrait of Yun Dongseom (1710–1795)', by: 'Unidentified artist', date: 'ca. 1790–1805', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/656430', focus: '50% 30%' },
  { id: 'hawk-at-sunrise', title: 'Hawk at Sunrise', by: 'Jeong Hong-Rae 정홍래 鄭弘來', date: 'second half 18th century–first half 19th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/860960', focus: '50% 30%' },
  { id: 'illustrated-legends-kitano-tenjin', title: 'Illustrated Legends of the Kitano Tenjin Shrine (Kitano Tenjin engi emaki)', by: 'Japan', date: 'late 13th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/45428' },
  { id: 'rough-waves', title: 'Rough Waves', by: 'Ogata Kōrin', date: 'ca. 1704–9', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/44918' },
  { id: 'gibbons-landscape', title: 'Gibbons in a Landscape', by: 'Sesson Shūkei 雪村周継', date: 'ca. 1570', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/44696' },
  { id: 'zao-gongen', title: 'Zaō Gongen', by: 'Japan', date: '11th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/39707', focus: '50% 30%' },
  { id: 'robe-shells-sea-grasses', title: 'Robe (Kosode) with Shells and Sea Grasses', by: 'Japan', date: 'early 17th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/50688', focus: '50% 30%' },
  { id: 'night-rain-at-double', title: 'Night Rain at the Double-Shelf Stand, from the series Eight Parlor Views (Zashiki hakkei)', by: 'Suzuki Harunobu', date: 'ca. 1766', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/37145', focus: '50% 30%' },
  { id: 'dancing-dervishes-divan-hafiz', title: '"Dancing Dervishes", Folio from a Divan of Hafiz', by: 'Hafiz', date: 'ca. 1480', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/446892', focus: '50% 30%' },
  { id: 'concourse-birds-11r-mantiq', title: '"The Concourse of the Birds", Folio 11r from a Mantiq al-Tayr (Language of the Birds)', by: 'Habiballah of Sava', date: 'ca. 1600', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/451725', focus: '50% 30%' },
  { id: 'feast-sada-22v-shahnama', title: '"The Feast of Sada", Folio 22v from the Shahnama (Book of Kings) of Shah Tahmasp', by: 'Abu\'l Qasim Firdausi', date: 'ca. 1525', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/452111', focus: '50% 30%' },
  { id: 'tahmuras-defeats-divs-23v', title: '"Tahmuras Defeats the Divs", Folio 23v from the Shahnama (Book of Kings) of Shah Tahmasp', by: 'Abu\'l Qasim Firdausi', date: 'ca. 1525', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/452112', focus: '50% 30%' },
  { id: 'isfandiyars-third-course-he', title: '"Isfandiyar\'s Third Course: He Slays a Dragon", Folio 434v from the Shahnama (Book of Kings) of Shah Tahmasp', by: 'Abu\'l Qasim Firdausi', date: 'ca. 1530', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/452160', focus: '50% 30%' },
  { id: 'garden-gathering', title: 'Garden Gathering', by: 'Iran', date: '1640–50', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/455082' },
  { id: 'mihrab', title: 'Mihrab (Prayer Niche)', by: 'Iran', date: 'dated 755 AH/1354–55 CE', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/449537', focus: '50% 30%' },
  { id: 'emperors-carpet', title: 'The Emperor\'s Carpet', by: 'Iran', date: 'second half 16th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/450509', focus: '50% 30%' },
  { id: 'star-ushak-carpet', title: '"Star Ushak" Carpet', by: 'Western Turkey', date: 'probably 17th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/447568', focus: '50% 30%' },
  { id: 'blue-quran', title: 'Folio from the "Blue Qur\'an"', by: 'Tunisia', date: 'second half 9th–mid-10th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/454662' },
  { id: 'damascus-room', title: 'Damascus Room', by: 'Syria', date: 'dated 1119 AH/1707 CE', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/452102', focus: '50% 30%' },
  { id: 'ceiling', title: 'Ceiling', by: 'Spain', date: '16th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/451373' },
  { id: 'akbar-lion-calf-shah', title: '"Akbar With Lion and Calf", Folio from the Shah Jahan Album', by: 'Govardhan', date: 'verso: ca. 1630; recto: ca. 1530–50', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/451268', focus: '50% 30%' },
  { id: 'shah-jahan-on-terrace', title: '"Shah Jahan on a Terrace, Holding a Pendant Set With His Portrait", Folio from the Shah Jahan Album', by: 'Chitarman', date: 'recto: dated 1627–28; verso: ca. 1530–50', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/451270', focus: '50% 30%' },
  { id: 'pierced-window-screen', title: 'Pierced Window Screen (Jali)', by: 'India', date: 'second half 16th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/453344', focus: '50% 30%' },
  { id: 'elephant-clock-book-knowledge', title: '"The Elephant Clock", Folio from a Book of the Knowledge of Ingenious Mechanical Devices by al-Jazari', by: 'Farrukh ibn `Abd al-Latif', date: 'dated 715 AH/1315 CE', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/451402', focus: '50% 30%' },
  { id: 'safavid-courtiers-leading-georgian', title: 'Safavid Courtiers Leading Georgian Captives', by: 'Iran', date: 'mid-16th century', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/451092', focus: '50% 30%' },
  { id: 'jonah-whale-probably-jami', title: '"Jonah and the Whale", Folio Probably from a Jami al-Tavarikh (Compendium of Chronicles)', by: 'Iran', date: 'ca. 1400', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/453683' },
  { id: 'calligraphic-galleon', title: 'Calligraphic Galleon', by: '\'Abd al-Qadir Hisari', date: 'dated 1180 AH/1766–67 CE', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/454611' },
  { id: 'relief-nebhepetre-mentuhotep-ii', title: 'Relief of Nebhepetre Mentuhotep II and the Goddess Hathor', by: 'Egypt', date: 'ca. 2010–2000 B.C.', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/548212' },
  { id: 'sphinx-hatshepsut', title: 'Sphinx of Hatshepsut', by: 'Egypt', date: 'ca. 1473–1458 BCE', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/544442' },
  { id: 'temple-dendur', title: 'The Temple of Dendur', by: 'Nubia', date: 'completed by 10 CE', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/547802', focus: '50% 30%' },
  { id: 'portrait-boy-eutyches', title: 'Portrait of the Boy Eutyches', by: 'Egypt', date: '100–150 CE', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/547951', focus: '50% 30%' },
  { id: 'ceiling-painting-palace-amenhotep', title: 'Ceiling painting from the palace of Amenhotep III', by: 'Egypt', date: 'ca. 1386–1347 BCE', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/544502' },
  { id: 'hippopotamus', title: 'Hippopotamus ("William")', by: 'Egypt', date: 'ca. 1961–1878 B.C.', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/544227', focus: '50% 30%' },
  { id: 'travelling-boat-being-rowed', title: 'Travelling Boat being Rowed', by: 'Egypt', date: 'ca. 1981–1975 B.C.', source: 'The Met', url: 'https://www.metmuseum.org/art/collection/search/544214' },
]
